### PR TITLE
Removal of incorrect battery sensors and replacement with tested alternatives. 

### PR DESCRIPTION
**Pull request by Roving-Ronin**
Remove Battery 1 sensors:
1) STORAGE_UNIT_1_RATED_CHARGE_POWER
2) STORAGE_UNIT_1_RATED_DISCHARGE_POWER

Reason:  Testing conducted with a dual battery setup (10kWh + 5kWh capacity), whereby it has established that:
1) The data published was incorrect, and;
2) The data was being published in the wrong place/device.

i.e. The data for the tested site was reporting 7500W for rated dis/charge capacity for Battery 1. 
This is technically impossible as LUNA S0 is limited to 2500W (5kW capacity) and 5000W (10/15kWh capacity).
So what is happening is this sensor is reporting the dis/charge capacity for BOTH batteries, and this sensor is saying its the value for Battery 1 (only).

Solution: Replace by the introduction of sensors for:
- STORAGE_RATED_CAPACITY
- STORAGE_MAXIMUM_CHARGE_POWER, and;
- STORAGE_MAXIMUM_DISCHARGE_POWER.

______________________________________

Sensor replacemnt / additions:
1) Add inverter RATED_POWER to assist Energy Management Optimisations requiring this information.
2) Add inverter P_MAX to assist Energy Management Optimisations requiring this information.
3) Add Batteries STORAGE_RATED_CAPACITY, see above.
4) Add Batteries STORAGE_MAXIMUM_CHARGE_POWER, see above.
5) Add Batteries STORAGE_MAXIMUM_DISCHARGE_POWER, see above.

______________________________________

Refer:

[Feature Request]: Register: 37007 - batteries_rated_charge_power - https://github.com/wlcrs/huawei_solar/issues/745
[Feature Request]: Register: 37009 - batteries_rated_discharge_power - https://github.com/wlcrs/huawei_solar/issues/746
[Feature Request]: Register: 37758 - batteries_rated_capacity - https://github.com/wlcrs/huawei_solar/issues/749
[Feature Request]: Register: 30073 - inverter_rated_power  - https://github.com/wlcrs/huawei_solar/issues/748
[Feature Request]: Register: 30075 - inverter_maximum_active_power - https://github.com/wlcrs/huawei_solar/issues/747

### CODE REVIEW

**Review by heinemannj — CHANGES_REQUESTED** [review]
Changes as stated in my issues are implemented since more then 2 weeks and are working as expected.

In addition I've downloaded and upgraded the complete huawei_solar integration manually:

- HA system log is clean

**Battery 1 Removal failed:**

image

**Batteries: Adding is OK**

image

**Inverter: Adding is OK**

image

**Comment by Roving-Ronin** [comment]
@heinemannj All works fine on the remote system I have access to for testing with 2 x L1 5kW and 1 x 15kW LUNA S0.  The Battery 1 - Diagnostic:
  - Rated Charge Power
  - Rated Discharge Power

also deleted fine in my case. When you open those no longer used sensors, do they say (I forget the official wording) but no longer used and the 'delete' button is available in the button left side of the card? If not, have you also tried checking in Developer Tools --> Statistics and seeing if they appear there with a 'Fix Issue' and delete them there?

**Review by heinemannj — COMMENTED** [review]
@wlcrs: You are completely right - I#ve overseen this important entity_registry_enabled_default parameter ... #() - Many thanks

**Comment by wlcrs** [comment]
Thank you for this PR. I've disabled these sensors by most people won't need them: they contain static information and are thus of little interest to keep track of. This prevents a performance hit for those who don't need it, but still allows you to enable them if you really want them.

**Comment by Roving-Ronin** [comment]
Hi Thijs,

Thanks for that, wasn't sure where to do that (disable by default).

BTW would it be possible (and best way for working on adding EMMA sensors) if you could create a new 'EMMA' branch, that we can then add PULL requests to, so you can accept them into that branch and when ready can then merge EMMA into Main ?

**Pull request merged**
