### PR TITLE
Clarify WiFi AP connectivity requirements

### PR DESCRIPTION
**Pull request by JohnMcLear**

### CODE REVIEW

**Comment by wlcrs** [comment]
Thank you for your contribution. Greatly appreciated!

**Comment by malteger** [comment]
I am not sure that this is correct. I am on a recent firmware, and it works with the SDongle connected to my network. The inverter (model SUN2000-6KTL-M1) is on firmware version `V100R001C00SPC141`, the dongle on `V100R001C00SPC127` (I do not know if that is the latest version, is there an overview on that? It has been updated this year to the then recent version.).

Based on #52 it looks like you have a SUN2000L and I found some similar reports [here](https://forum.huawei.com/enterprise/en/cant-connect-to-inverter-modbus-tcp-v200r001c00spc117-sun2000-6ktl-l1/thread/816679-100027), maybe the situation is different for SUN2000MA and SUN2000L inverters. Maybe it would be better to include Version numbers when mentioning what is working.

**Comment by javierin** [comment]
I can also connect myself to a SUN2000-5KTL-L1 using the Dongle ethernet IP address. It has been working fine since the last huawei mess-up. 
Previously the SDongle did not even answer on port 502 of the ethernet IP, but that was corrected back around December.

**Comment by madimadi** [comment]
FYI
I am happily connecting to the TCP/502 on IP address assigned by my Wifi router to the inverter. I do not connect to the Wifi AP of the inverter.

Inverter SUN2000-10KTL-M1:
V100R001C00SPC141

Dongle SDongleA:
V100R001C00SPC125

**Pull request merged**
