### PR TITLE
Update sensor.py - Add Battery(s) Temperature

### PR DESCRIPTION
**Pull request by Roving-Ronin**
Thijs,

Could we please add the battery temperature sensors in by default to the integration?

This file adds battery temperature sensors for Battery 1 and 2 added to v1.3.2, instead of not having the sensors included I would politely suggest that this should be included as battery temperature is important to monitor, with higher temperatures affecting the overall longevitity / charge cycles that a battery will last for/retain less charge over time.

Your consideration is greatly appreciated.

### CODE REVIEW

**Comment by spelzl** [comment]
+ 1 who would like to get the temperature(s) added into the integration.
Thank you Thijs & Roving

**Comment by Roving-Ronin** [comment]
@spelzl I've got a few sites working on this card, just working on helping a user get it working with 1 x M1 10kW and 2 x LUNA 15kWh, with the temperature in this card showing whichever of the batteries has the higher temperature, so action can be taken.

image

 Temp is just above the 'nipple' of the battery icon. Bad picture as battery SoC is low, normally it has a colour gradient based upon charge level and the battery outline changes to the colour of the power source charging it (i.e. Orange = Solar. Red (as in $) = Grid).

**Comment by spelzl** [comment]
@Roving-Ronin **Nice** 
Is this illustrated within HA? Is this designed via a custom card?
How do you manage four strings with only one inverter? Optimisers installed?

**Comment by Roving-Ronin** [comment]
HA Card - https://github.com/slipx06/sunsynk-power-flow-card

I've been working on getting Huawei (with WLCRS supported) and currently just writing up all the examples, code to paste into the card to work for Huawei and then all the derived (from WLCRS) sensors that are needed to be added.

Due to size of the card it currently supports showing 1 inverter and battery, but the derived sensors being made then work around it by adding sensor.inverters_xxxx / sensor.batteries_xxx etc and providing sum of inverters active power etc, temperature for inverters or batteries will show the higher of the two devices (so you can be alerted and jump on the issue).

**Comment by spelzl** [comment]
Fantastic!.
Would you mind and prepared to share your code for the example, so it can be used as a template?

**Comment by Roving-Ronin** [comment]
This is getting off track for this posts purpose of the PULL REQUEST, so moving the discssion over to:  https://github.com/wlcrs/huawei_solar/discussions/632

**Comment by serbat** [comment]
+1 I would like these battery temperatures included in WCLRS by default

**Comment by Roving-Ronin** [comment]
Hi WLCRS.... any feedback ? Thanks.

**Comment by wlcrs** [comment]
I understand the utility of the battery temperature sensor to you, but this integration has to walk a fine line between general utility to the user and performance/usability.

Currently, there are (up to) 5 batched calls being done every update cycle. This PR would add 2 new calls, effectively increasing the number of calls by 40% and thus reducing the performance of this integration considerably. I'm therefore not going to merge it. 

I provided instructions and example code in https://github.com/wlcrs/huawei_solar/wiki/Defining-custom-sensors on how to add extra sensors so that users can make the tradeoff of adding extra sensors at will, but this is a personal choice and not something I will consider merging into the "mainstream" Huawei Solar integration.

**Comment by Roving-Ronin** [comment]
Thijs,

If these where to be implemented, BUT set to 'Disabled' (like other sensors the integration creates, such as sensor.power_meter_a_b_line_voltage on a 3p meter) would this still cause the integration to batch 2 more calls ?

Just trying to think out of the box, so users who require the battery temperature sensors could easily just enable them in the standard integration installation, but by default they would be off and not cause the overhead to those not needing them.  Or do they still get batched, even if disabled?

**Comment by wlcrs** [comment]
Let me phrase it otherwise: I'm not willing to take on the extra load of support requests that will come in when I would merge this PR. Not for the extra stability issues it would create due to the added calls, not for the lack of automatic detection whether these sensors even exist in the first place, not for future work to keep this new code up-to-date, not for the new PRs that would come in with even more sensors that are cherry-picked by other users.

I know that this sounds harsh, but I prefer to run a tight ship. I'd rather focus on having a functional and stable integration that works perfectly well and is feature-complete for 95% of the users than keep adding bells and whistles which blow up the complexity of the integration and make it a burden to maintain as a whole.

**Comment by bfroemel** [comment]
running a tight ship is ofc fine, but to be honest: the suggested way to add extra sensors is a lot more "advanced" (I'd rather say cumbersome) than it has to be, even for running a tight ship. From a user perspective it would be much nicer to just provide or edit some configuration than having to do code changes based on an example diff. Not only is the initial effort high (excluding a lot of non-coding ppl right away), one has to reapply their own code changes for every update of the integration.

Hence, I'd propose to consider another alternative: add (or allow for the addition of) minimal generic code to support user-defined extra sensors. The sensor definitions could be provided by an advanced user during the configuration flow, e.g., a yaml snippet. There you could also put a warning that anyone who uses this feature is on their own.

(by the way: battery temperature and insulation resistance are imo tremendously important safety indicators and have been part of the Huawei Modbus interface definition since ... (the very first releases of inverters and hybrid inverters?). I am surprised that they are considered almost as exotic sensor values not relevant for most users.)

**Comment by wlcrs** [comment]
Closing in favor of the new dynamic approach forthcoming in v1.4.0.

Please help to test [alpha release v1.4.0 alpha 1](https://github.com/wlcrs/huawei_solar/releases/tag/1.4.0a1)

**Pull request closed without merging**
