### PR TITLE
Update it.json

### PR DESCRIPTION
**Pull request by alexdelli**
Add Power Meter prefix to Power Meter Active Power to identify this sensor instead of Active Power

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Prefix? :P

**Comment by alexdelli** [comment]
> Prefix? :P

yes, sorry :)

**Comment by wlcrs** [comment]
I'm a bit hesitant to merge this, as it does not conform to the "Entity naming" conventions of HA.

I properly set the name of the power meter "device" in HA to "Power meter", and thus HA should combine the device name and entity name to create the correct `friendly_name` if necessary. Going against this, risks us getting entities called "Power meter Power Meter Potenza attiva" and sensor ids like `sensor.power_meter_power_meter_potenza_attiva`. This does not look like an improvement...

More info: 
- https://developers.home-assistant.io/blog/2022/07/10/entity_naming/
- https://developers.home-assistant.io/docs/core/entity/#entity-naming

**Comment by alexdelli** [comment]
Before of this adjustment I had only sensor.potenza_attiva, but it was the
same as per inverter
Now it is sensor.power_meter_potenza_attiva


Sent from Gmail Mobile


Il giorno ven 19 gen 2024 alle 18:07 Thijs W. ***@***.***> ha
scritto:

**Pull request closed without merging**
