### PR TITLE
Update sensor.py

### PR DESCRIPTION
**Pull request by peetersch**
Assign the correct device_class and state_class to the storage unit day charge/discharge and total charge/discharge entities.

### CODE REVIEW

**Comment by wlcrs** [comment]
Can you please explain why you think that these values need to be changed?

What did I understand wrong after reading https://developers.home-assistant.io/docs/core/entity/sensor?_highlight=total_inc#entities-representing-a-total-amount ?

**Comment by peetersch** [comment]
Hi, I noticed this because the all generate warnings in the log.
None of them can have device_class energy_storage as none of them represent
the level of the storage, each  of them only has 50% of the level change,
one has only the charge part and the other the discharge_part.
So they are just ‘Energy’.
For the total entities, as they are always increasing (both charge and
discharge), we can put sensor class total_increasing.
For the day entities, they can only have sensor class total, because they
are reset every day at midnight, so they are not always increasing (and
this would also trigger warnings in the log)
I also don’t understand why there is the word capacity in the day
charge/dischage entity keys.
For me, they have nothing to do with capacity.
They day entities are the same as the total obes, but just not reset every
day.
I also tested my proposed change, and now there are mo more warnings 😀

Hope this helps

**Comment by peetersch** [comment]
After reading again the link you provided, maybe it’s also possible to put
total_increasing for the day_entities, because they reset every night to
exactly 0KWH. I never tested this, but according to what I read in the
documentation , resetting to 0 should nit generate warnings. So probably
it’s better to put total_increasing on all 4.

**Comment by Mckill3r** [comment]
@peetersch Hello, can you provide us with your update on sensors and confirm that everything works the same :)

Juste want to have a clean logs.

Thanks

**Comment by peetersch** [comment]
[https://github.com/wlcrs/huawei_solar/pull/817/files#diff-adf648fcc09089e05b962654454a3cbdfcfe9884f8feee8c10fb6bee086a859d]
[](url)

> @peetersch Hello, can you provide us with your update on sensors and confirm that everything works the same :)
> 
> Juste want to have a clean logs.
> 
> Thanks

Yes, you can find my changes to the sensor.py file here:
https://github.com/wlcrs/huawei_solar/pull/817/files#diff-adf648fcc09089e05b962654454a3cbdfcfe9884f8feee8c10fb6bee086a859d
I tested them, and after these changes, there are no more warnings in the log file.

**Pull request merged**
